force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>ORD-{0000000}</displayFormat>
        <label>Order</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Purchase Orders</relationshipLabel>
    <relationshipName>PO_Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/BILLINGCITY__c.field-meta.xml
<CustomField>
    <fullName>BILLINGCITY__c</fullName>
    <label>Billing City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/BILLINGCOUNTRY__c.field-meta.xml
<CustomField>
    <fullName>BILLINGCOUNTRY__c</fullName>
    <label>Billing Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/BILLINGPOSTALCODE__c.field-meta.xml
<CustomField>
    <fullName>BILLINGPOSTALCODE__c</fullName>
    <label>Billing Postal Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/BILLINGSTATE__c.field-meta.xml
<CustomField>
    <fullName>BILLINGSTATE__c</fullName>
    <label>Billing State</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/BILLINGSTREET__c.field-meta.xml
<CustomField>
    <fullName>BILLINGSTREET__c</fullName>
    <label>Billing Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/SHIPPINGCITY__c.field-meta.xml
<CustomField>
    <fullName>SHIPPINGCITY__c</fullName>
    <label>Shipping City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/SHIPPINGCOUNTRY__c.field-meta.xml
<CustomField>
    <fullName>SHIPPINGCOUNTRY__c</fullName>
    <label>Shipping Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/SHIPPINGPOSTALCODE__c.field-meta.xml
<CustomField>
    <fullName>SHIPPINGPOSTALCODE__c</fullName>
    <label>Shipping Postal Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/SHIPPINGSTATE__c.field-meta.xml
<CustomField>
    <fullName>SHIPPINGSTATE__c</fullName>
    <label>Shipping State</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/SHIPPINGSTREET__c.field-meta.xml
<CustomField>
    <fullName>SHIPPINGSTREET__c</fullName>
    <label>Shipping Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OrderUtility.cls
public inherited sharing class OrderUtility {
    public OrderUtility() {

    }

    public static Order__c defaultOrderAddress(Account acc, Order__c ord){
        if(ord.AccountId__c != null){
            //Populating Default Order BIlling address with Account Billing Address
            Address billingAddr = (Address) acc.BillingAddress;
            ord.BillingStreet__c = billingAddr.getStreet();
            ord.BILLINGCITY__c = billingAddr.getCity();
            ord.BILLINGSTATE__c = billingAddr.getState();
            ord.BILLINGCOUNTRY__c = billingAddr.getCountry();
            ord.BILLINGPOSTALCODE__c = billingAddr.getPostalCode();
            
            //Populating Default Order Shipping address with Account Shipping Address.
            Address shippingAddr = (Address) acc.ShippingAddress;
            ord.SHIPPINGStreet__c = shippingAddr.getStreet();
            ord.SHIPPINGCITY__c = shippingAddr.getCity();
            ord.SHIPPINGSTATE__c = shippingAddr.getState();
            ord.SHIPPINGCOUNTRY__c = shippingAddr.getCountry();
            ord.SHIPPINGPOSTALCODE__c = shippingAddr.getPostalCode();
        }
        return ord;
    }
}